### ISSUE TITLE
Why is it not possible to control the RGB?

### ISSUE THREAD

**Issue by majuss** [dr1rrb/py-twinkly-client#3]
What is the exact reason that we can't control the rgb flow?

**Comment by majuss** [comment]
These guys: https://github.com/linkineo/tinky-twinkly/blob/master/xmas.js seem to be able to change the color etc.

**Comment by majuss** [comment]
This library seems to be way more powerful: https://github.com/scrool/xled

**Comment by dr1rrb** [comment]
> 
> 
> What is the exact reason that we can't control the rgb flow?

Well, the only reason is that I didn't spent enough time on this :) My main idea was to configure effect of my Christmas tree using the native app, and then turn it on/off from home assistant (and more specifically from automation !).

But I plan to work on the HA component soon, starting by removing my cheap client and use a more powerful.

**Comment by majuss** [comment]
xled seem to fit the job quite nicely. Thank you for your efforts!
